# Generated by Django 2.1.4 on 2018-12-04 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'EventTable',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('team1_score', models.IntegerField()),
                ('team2_score', models.IntegerField()),
            ],
            options={
                'db_table': 'GameTable',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('win_count', models.IntegerField()),
                ('loss_count', models.IntegerField()),
                ('tie_count', models.IntegerField()),
            ],
            options={
                'db_table': 'TeamTable',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('is_leader', models.BooleanField(default=False)),
                ('receive_reminder', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'UserTable',
            },
        ),
    ]
