# Generated by Django 2.1.4 on 2018-12-05 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
