# Generated by Django 2.1.4 on 2018-12-12 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee', '0002_auto_20181212_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
