# Generated by Django 2.1.4 on 2018-12-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee', '0002_auto_20181210_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_open',
        ),
        migrations.AddField(
            model_name='event',
            name='teams',
            field=models.ManyToManyField(to='frisbee.Team'),
        ),
    ]
