# Generated by Django 2.1.4 on 2018-12-11 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee', '0004_auto_20181208_2224'),
        ('frisbee', '0003_auto_20181210_1941'),
    ]

    operations = [
    ]
