# Generated by Django 2.1.4 on 2018-12-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee', '0007_auto_20181211_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
