# Generated by Django 2.1.4 on 2018-12-12 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee', '0008_user_is_active'),
        ('frisbee', '0003_auto_20181212_0047'),
    ]

    operations = [
    ]
