# Generated by Django 2.1.4 on 2018-12-12 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frisbee', '0009_merge_20181212_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='has_schedule',
            field=models.BooleanField(default=False),
        ),
    ]
